### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by aodjo** [aabssmc/Skuishy#14]
```
00:18:04 | #!#! [Skript] Severe Error:00:18:04 | #!#! 00:18:04 | #!#! Something went horribly wrong with Skript.00:18:04 | #!#! This issue is NOT your fault! You probably can't fix it yourself, either.00:18:04 | #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).00:18:04 | #!#! Here is full list of them:00:18:04 | #!#! Skuishy v2.8.1 (https://aabss.cc) 00:18:04 | #!#! We could not identify which of those are specially related, so this might also be Skript issue.00:18:04 | #!#! You should try disabling those plugins one by one, trying to find which one causes it.00:18:04 | #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.00:18:04 | #!#! In that case, you will be given instruction on how should you report it.00:18:04 | #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.00:18:04 | #!#! Only if the author tells you to do so, report it to Skript's issue tracker.00:18:04 | #!#! 00:18:04 | #!#! Stack trace:00:18:04 | #!#! java.lang.IllegalStateException: zip file closed00:18:04 | #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)00:18:04 | #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)00:18:04 | #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)00:18:04 | #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)00:18:04 | #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)00:18:04 | #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)00:18:04 | #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)00:18:04 | #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)00:18:04 | #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)00:18:04 | #!#!     at Skript-2.9.5.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)00:18:04 | #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)00:18:04 | #!#!     at com.google.gson.Gson.toJson(Gson.java:834)00:18:04 | #!#!     at com.google.gson.Gson.toJson(Gson.java:812)00:18:04 | #!#!     at com.google.gson.Gson.toJson(Gson.java:759)00:18:04 | #!#!     at com.google.gson.Gson.toJson(Gson.java:736)00:18:04 | #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:178)00:18:04 | #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:18)00:18:04 | #!#!     at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3430)00:18:04 | #!#!     at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3418)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.effects.EffActionBar.execute(EffActionBar.java:69)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:121)00:18:04 | #!#!     at Skript-2.9.5.jar//ch.njol.skript.events.EvtPeriodical.lambda$postLoad$0(EvtPeriodical.java:80)00:18:04 | #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)00:18:04 | #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)00:18:04 | #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804)00:18:04 | #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665)00:18:04 | #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330)00:18:04 | #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)00:18:04 | #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)00:18:04 | #!#! 00:18:04 | #!#! Version Information:00:18:04 | #!#!   Skript: 2.9.5 (latest)00:18:04 | #!#!     Flavor: skriptlang-github00:18:04 | #!#!     Date: 19:09:25.85835620000:18:04 | #!#!   Bukkit: 1.21.3-R0.1-SNAPSHOT00:18:04 | #!#!   Minecraft: 1.21.300:18:04 | #!#!   Java: 21.0.4 (Java HotSpot(TM) 64-Bit Server VM 21.0.4+8-LTS-274)00:18:04 | #!#!   OS: Windows 11 amd64 10.000:18:04 | #!#!00:18:04 | #!#! Server platform: Paper00:18:04 | #!#! 00:18:04 | #!#! Current node: null00:18:04 | #!#! Current item: send action bar "Server Uptime: §a%uptime%" to loop-player00:18:04 | #!#! Current trigger: every 0.1 seconds (every 0.1 seconds) (scoreboard.sk, line 17)00:18:04 | #!#! 00:18:04 | #!#! Thread: Server thread00:18:04 | #!#! 00:18:04 | #!#! Language: english00:18:04 | #!#! Link parse mode: DISABLED00:18:04 | #!#! 00:18:04 | #!#! End of Error.
```

**Comment by aream2** [comment]
I solved this issue. It was a problem with the Skript itself.

**Comment by aodjo** [comment]
I solved this issue. It was a problem with the Skript itself.
